Updated from VGGLoss to LPIPSLoss
There are still errors on module.py

 File "/content/drive/MyDrive/SRGAN-PyTorch-master-N-Funcional/train.py", line 589, in <module>
    main()
  File "/content/drive/MyDrive/SRGAN-PyTorch-master-N-Funcional/train.py", line 153, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "/content/drive/MyDrive/SRGAN-PyTorch-master-N-Funcional/train.py", line 391, in main_worker
    args=args)
  File "/content/drive/MyDrive/SRGAN-PyTorch-master-N-Funcional/train.py", line 543, in train_gan
    content_loss = content_criterion(sr, hr.detach())
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/SRGAN-PyTorch-master-N-Funcional/srgan_pytorch/loss.py", line 207, in forward
    loss = torch.nn.functional.mse_loss(self.features(source), self.features(target))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'in1'